
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always 

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    expose:
      - "${PORT}"
    env_file:
      - ./.env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
    


